### ISSUE TITLE
Use-Contractkit Network Change Request is Ineffective

### ISSUE THREAD

**Issue by aslawson** [celo-org/use-contractkit#64] opened 2021-11-15 17:39 UTC
Reported by @jmrossy 
https://celo-org.slack.com/archives/C025JMEQVEW/p1636316811012300

**Comment by jmrossy** [comment] 2021-11-16 11:37
Steps to repo:
1. Start use-ck, it connects to Mainnet
2. Use updateNetwork to switch to Alfajores
3. Refresh the page, it’s actually connected to Alfajores but `const { network } = useContractKit()` returns Mainnet as the network value.
4. Calling updateNetwork with Mainnet does nothing, presumably because it believes it’s already connected there

**Comment by jmrossy** [comment] 2021-11-16 11:38
Semi-separate issue but that may have the same root cause:
The network of connected extension wallets (e.g. Metamask) take precedence over the `updateNetwork` calls. Changing the network in Metamask changes the network for use-ck, but it still returns the old value

**Comment by dckesler** [comment] 2021-12-08 17:04
This should be fixed now in the latest versions

**Closed by dckesler** 2021-12-08 17:04 UTC
Labels: bug, Applications, investigation, Priority: P1
