### ISSUE TITLE
use-contractkit with react-native

### ISSUE THREAD

**Issue by obernardovieira** [celo-org/use-contractkit#70] opened 2021-11-22 12:55 UTC
Hi, I was trying to use `use-contractkit` but it didn't work, and seems like a couple of things need to be changed in order to make it work.
Do you have any plans on making those changes? Is it even reasonable to have a modal, or should it always default to wallet connect when calling from react-native?

Actually, I felt that even when using mobile browser. Why even show the modal?

**Comment by jmrossy** [comment] 2021-11-22 15:04
Closing as dupe of #https://github.com/celo-org/use-contractkit/issues/21

**Closed by jmrossy** 2021-11-22 15:04 UTC
